# Generated by Django 2.2.13 on 2020-10-21 21:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='settings',
            name='number_format',
            field=models.CharField(choices=[('currency_standard', '1,234.56'), ('number_standard', '1234.56'), ('currency_rounded', '1,235'), ('number_rounded', '1235')], default='currency_standard', max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bank Account'), (1, 'Savings Account'), (2, 'Pension'), (3, 'Cash'), (4, 'Asset'), (5, 'Liability')], default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP (£)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='GBP', max_length=3),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('title', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='app.Account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='app.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
    ]
