# Generated by Django 2.2.13 on 2020-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200716_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='number_format',
            field=models.CharField(choices=[('GBP', '%s (%s)'), ('USD', '%s (%s)'), ('EUR', '%s (%s)')], default='currency_standard', max_length=32),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('GBP', '%s (%s)'), ('USD', '%s (%s)'), ('EUR', '%s (%s)')], default='GBP', max_length=3),
        ),
    ]
