# Generated by Django 2.2.13 on 2020-07-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200716_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP (£)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='number_format',
            field=models.CharField(choices=[('currency_standard', '1,234.56'), ('number_standard', '1234.56'), ('currency_rounded', '1,235'), ('number_rounded', '1235')], default='currency_standard', max_length=32),
        ),
    ]
