# Generated by Django 2.2.13 on 2020-07-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200718_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bank Account'), (1, 'Savings Account'), (2, 'Pension'), (3, 'Cash'), (4, 'Asset'), (5, 'Liability')], default=0),
        ),
    ]
