# Generated by Django 2.2.13 on 2020-07-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200720_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='app.Account'),
        ),
    ]
