# Generated by Django 2.2.13 on 2020-07-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200723_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='initial_balance',
        ),
    ]
